apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-keyvault-team-2
  namespace: api
spec:
  provider: azure
  parameters:
    keyvaultName: "aks-keyvault-team-2"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "9bd405d9-5112-4d75-8544-bd8d031d17f4" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQLPASSWORD      # In this example, 'ExampleSecret' 
          objectAlias: SQL_PASSWORD     # [OPTIONAL] specify the filename of the object when written to disk - defaults to objectName if not provided
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLSERVER      # In this example, 'ExampleSecret' 
          objectAlias: SQL_SERVER     # [OPTIONAL] specify the filename of the object when written to disk - defaults to objectName if not provided
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLUSER      # In this example, 'ExampleSecret' 
          objectAlias: SQL_USER     # [OPTIONAL] specify the filename of the object when written to disk - defaults to objectName if not provided
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty 
        - |
          objectName: DATABASENAME      # In this example, 'ExampleSecret' 
          objectAlias: SQL_DBNAME     # [OPTIONAL] specify the filename of the object when written to disk - defaults to objectName if not provided
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty 
    tenantId: "21a16a8f-3164-4882-997a-29873cd5b0b2"               # the tenant ID containing the Azure Key Vault instance