apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: default
  labels:
    app: trips-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips-deployment
  template:
    metadata:
      labels:
        app: trips-deployment
    spec:
      containers:
      - name: trips-deployment
        image: "registryszc7583.azurecr.io/trips:1.0"
        ports:
        - containerPort: 80
        env:
        envFrom:
        - secretRef:
           name: sql
        # not required, but recommended best practice
        livenessProbe:
          httpGet:
            path: "/api/trips/healthcheck" # hint: there is a healthcheck endpoint - read the README!
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: "/"
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        # resource limits are also best practice - I'll let you figure that out on your own

---
apiVersion: v1
kind: Service
metadata:
  name: trips-deployment
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: trips-deployment
  ports:
    - protocol: TCP
      name: trips-http
      port: 80 # port you hit
      targetPort: 80 # port inside container